# Generated by Django 4.2.16 on 2026-04-23 16:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompoundReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('compound_code', models.CharField(max_length=30, unique=True)),
                ('compound_name', models.CharField(max_length=150)),
                ('compound_class', models.CharField(blank=True, max_length=100)),
                ('cas_number', models.CharField(blank=True, max_length=30)),
                ('pnec_eco_value', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('pnec_amr_value', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('pnec_unit', models.CharField(choices=[('ng/L', 'ng/L'), ('μg/L', 'μg/L'), ('mg/L', 'mg/L')], default='μg/L', help_text='Unit that PNEC values are stored in', max_length=10)),
                ('preferred_calc_unit', models.CharField(choices=[('ng/L', 'ng/L'), ('μg/L', 'μg/L'), ('mg/L', 'mg/L')], default='μg/L', help_text='Unit to use during RQ calculation. Input MEC will be converted to this unit.', max_length=10)),
                ('pnec_source', models.CharField(blank=True, max_length=200)),
                ('pnec_source_year', models.IntegerField(blank=True, null=True)),
                ('reference_citation', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'compound_reference',
                'ordering': ['compound_name'],
            },
        ),
    ]
