# Generated by Django 4.2.16 on 2026-08-04 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PathogenProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pathogen_name', models.CharField(max_length=150, unique=True)),
                ('display_strain', models.CharField(blank=True, max_length=150)),
                ('model_type', models.CharField(choices=[('exponential', 'Exponential'), ('beta_poisson', 'Beta-Poisson')], max_length=20)),
                ('alpha', models.FloatField(blank=True, help_text='Beta-Poisson α parameter', null=True)),
                ('beta', models.FloatField(blank=True, help_text='Beta-Poisson β parameter', null=True)),
                ('k', models.FloatField(blank=True, help_text='Exponential k parameter', null=True)),
                ('illness_ratio', models.FloatField(help_text='Fraction of infected individuals who develop illness')),
                ('daly_weight', models.FloatField(help_text='DALYs per illness case (WHO GDWQ disability weight)')),
                ('param_source', models.CharField(default='QMRAWiki', max_length=250)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pathogen_profile',
                'ordering': ['pathogen_name'],
            },
        ),
    ]
