# Generated by Django 4.2.16 on 2026-08-04 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_qmra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathogenprofile',
            name='created_by',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pathogenprofile',
            name='updated_by',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
