# Generated by Django 4.2.16 on 2026-08-25 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_qmra', '0002_add_created_by_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathogenprofile',
            name='endpoint_daly_params',
            field=models.JSONField(blank=True, default=dict, help_text='Per-endpoint DALY parameters: {endpoint: {cfr_baseline, cfr_resistant, duration_baseline_days, duration_resistant_days, disability_weight}}'),
        ),
        migrations.AddField(
            model_name='pathogenprofile',
            name='life_expectancy_at_death',
            field=models.FloatField(default=43.4, help_text='L_YLL: standard life expectancy minus median age at infection (years)'),
        ),
        migrations.AddField(
            model_name='pathogenprofile',
            name='param_source_amr',
            field=models.CharField(blank=True, help_text='Citation for AMR-specific DALY parameters', max_length=250),
        ),
        migrations.AddField(
            model_name='pathogenprofile',
            name='pathogenic_fraction',
            field=models.FloatField(default=1.0, help_text='Fraction of total organism count that is pathogenic (e.g. 0.08 for total E. coli counts)'),
        ),
        migrations.AddField(
            model_name='pathogenprofile',
            name='resistant_illness_ratio',
            field=models.FloatField(blank=True, help_text='Illness ratio for resistant strain (None = same as baseline)', null=True),
        ),
        migrations.AlterField(
            model_name='pathogenprofile',
            name='daly_weight',
            field=models.FloatField(default=0.0, help_text='Legacy single DALY weight — superseded by endpoint_daly_params'),
        ),
    ]
