# Generated by Django 4.2.16 on 2026-04-23 16:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module_code', models.CharField(max_length=50, unique=True)),
                ('module_name', models.CharField(max_length=100)),
                ('module_description', models.TextField(blank=True)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('risk_thresholds', models.JSONField(help_text='JSON: {"levels": [{"label": "Low Risk", "min": 0, "max": 1, "color": "#059669"}, ...]}')),
                ('calculation_config', models.JSONField(default=dict, help_text='Module-specific calculation parameters (formula, PNEC source table, etc.)')),
                ('input_schema', models.JSONField(default=dict, help_text='Expected Excel template structure: required columns, unit row, data start row')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'module_config',
                'ordering': ['module_code'],
            },
        ),
    ]
