# Generated by Django 4.2.16 on 2026-09-21 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduleconfig',
            name='infection_risk_thresholds',
            field=models.JSONField(blank=True, default=dict, help_text='JSON: {"benchmark": 1e-4, "levels": [...]}'),
        ),
    ]
